spring.application.name=BankSpringBoot

spring.datasource.url=jdbc:postgresql://mouse.db.elephantsql.com:5432/baozhnko
spring.datasource.username=baozhnko
spring.datasource.password=EmBFgxRxbXKOFxhmcm4tEcDCnP2Jr5_f

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update


logging.level.org.hibernate.SQL=debug
spring.jpa.hibernate.naming.physical-strategy = org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jackson.time-zone=America/Bogota
spring.jackson.locale=es_CO
server.port =8094
